name: Update Lowest‐Ask Prices

permissions:
  contents: write

on:
  schedule:
    - cron: '0 * * * *'    # every hour
  workflow_dispatch:      # manual trigger

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run price updater
        run: node updatePrices.js

      - name: Commit & push changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "chore: update lowest‐ask prices via Roblox API"
          push: true
