name: Update Limited Prices

# Run every hour and on manual trigger
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out code
      - uses: actions/checkout@v3

      # 2) Install Node
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3) Install dependencies
      - run: npm ci

      # 4) Run the updater script
      - run: node scripts/updatePrices.js

      # 5) Commit & push changes if any
      - uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "chore: update limited lowest-ask prices"
          push: true
